name: flutterend
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2
  http: ^1.2.0
  flutter_slidable: ^3.0.1
  logger: ^2.1.0
  platform_device_id: ^1.0.1
  url_launcher: ^6.2.5
  easy_localization: ^3.0.5
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_storage: ^2.1.1
  firebase_core: ^2.26.5
  firebase_auth: ^4.17.5
  firebase_database: ^10.4.5
  firebase_storage: ^11.6.5
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
